import { Text } from '@chakra-ui/react'
import Head from 'next/head'
import { Header } from '../components/Header'
import { Home } from '../components/Home'

export default function App() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Home />
    </>
  )
}
